'use client';
// import type { Metadata } from 'next';
import { Mulish, Lato } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import Sidebar from '@/components/sidebar';
import Header from '@/components/header';
import { usePathname } from 'next/navigation';

const mulish = Mulish({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--mulish-font',
  display: 'swap',
});

const lato = Lato({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  variable: '--lato-font',
  display: 'swap',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const excludedPaths = ['/login'];
  const showSidebarAndHeader = !excludedPaths.includes(pathname);
  return (
    <html lang="en">
      <Providers>
        <body className={`${mulish.variable} ${lato.variable} antialiased`}>
          <div className="flex">
            {showSidebarAndHeader && <Sidebar />}

            <div className="w-full">
              {showSidebarAndHeader && <Header brandName="Ankit" />}
              {children}
            </div>
          </div>
        </body>
      </Providers>
    </html>
  );
}
